"""add description to concept_queues

Revision ID: 0f42ecbc1e99
Revises: 64051568cb6f
Create Date: 2020-06-06 17:04:24.412106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f42ecbc1e99'
down_revision = '64051568cb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_queues', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_queues', 'description')
    # ### end Alembic commands ###
