"""create concept_queues_entries table

Revision ID: 64051568cb6f
Revises: 1cbb2b289548
Create Date: 2020-05-30 19:31:49.055772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64051568cb6f'
down_revision = '1cbb2b289548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_queues_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('conceptQueueId', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['conceptQueueId'], ['concept_queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_queues_entries_state'), 'concept_queues_entries', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_queues_entries_state'), table_name='concept_queues_entries')
    op.drop_table('concept_queues_entries')
    # ### end Alembic commands ###
